# config/sgd_config.yaml

# -----------------------------
# Model configuration
# -----------------------------
model:
  name: "VGG-base"
  num_classes: 10

# -----------------------------
# Data configuration
# -----------------------------
data:
  root: "./data"
  augmentation:
    normalize_mean: [0.4914, 0.4822, 0.4465]
    normalize_std: [0.247, 0.243, 0.261]

# -----------------------------
# Training configuration
# -----------------------------
training:
  device_ids: [0]
  target_gpu_id: 0
  num_workers: 64
  batch_size: 128
  seed_value: 2020
  epochs: 200

# -----------------------------
# Optimizer configuration（SGD + momentum）
# -----------------------------
optimizer:
  type: "SGD"              # 优化器类型：SGD
  lr: 0.01                 # 学习率
  momentum: 0.9            # 动量参数
  weight_decay: 0.0005       # L2 正则化

scheduler:
  type: "CosineAnnealingLR"
  params:
    T_max: 200          # 一个完整周期为 200 个 epoch
    eta_min: 0.000001       # lr 在最低点时的最小值

# （此处同样不使用 scheduler，如果需要可参考第 3 个示例）

# -----------------------------
# Paths for saving outputs
# -----------------------------
paths:
  figures: "reports/figures/ablation-optimizer/sgd"                        # Relative path from project root
  models: "reports/models/ablation-optimizer/sgd"                          # Relative path from project root
  training_data: "reports/training_data/ablation-optimizer/sgd"            # Relative path from project root
  best_model_filename: "vgg_a_cifar10_best.pth"     # Filename for best model checkpoint
  landscape_plot_filename: "loss_landscape_indicator.png"  # Filename for the loss landscape plot
  step_records_filename: "step_metrics.csv"
  epoch_metrics_filename: "epoch_metrics.csv"
